### PR TITLE
fix saver name

### PR DESCRIPTION
**Pull request by jojonki**
The name of `Saver()` instance looks `saver` not `full_saver`

### CODE REVIEW

**Comment by anilkumar2444** [comment]
In the paper, the official evaluation metric is F1 score, but I couldn't find the code to compute F1 score. Can  you please tell me where can I find the code to compute F1 score.

**Comment by sivareddyg** [comment]
Hi Anil,

Try this:
https://github.com/sivareddyg/graph-parser/blob/master/data/spades/spades_evaluation.py

Cheers,
Siva

**Comment by anilkumar2444** [comment]
Hi sivareddy sir,
I understood two arguments to spades_evaluation.py are some text files, but I couldn't find those files and I couldn't understand the format of those files. Can you please help me to find those files.

Thank you.

**Comment by anilkumar2444** [comment]
Hello,
The test results file you uploaded is giving around an accuracy of 39. But when I train the model by myself it is giving the only accuracy of 28 on the test set with only KB (without text KB).  But in the paper, it is written that only KB also will give an accuracy(almost equal to F1 score) of 38. I don't understand where am I doing wrong. I haven't changed the code except for one line which is "use_text = 1" in config.sh file. Can u please help me to get the result mentioned in the paper.

**Pull request merged**
